geometries:
  - name: hello1
    file: hello1.obj
  - name: hello2
    file: hello2.obj
  - name: hello3
    file: hello3.obj
  - name: hello9
    file: hello9.obj
  - name: line
    file: line.obj
  - name: triangle
    file: triangle.obj
    removeCrossbar: false
  - name: rectangle
    file: rectangle.obj
  - name: cube
    file: cube.obj
  - name: cylinder
    file: cylinder.obj
  - name: sphere
    file: sphere.obj
    #  - name: ballerina
    #    file: ballerina.obj
